import { Platform, StyleSheet } from 'react-native';

export const getColors = (isDark) => ({
  background: isDark ? '#0F172A' : '#FFF',
  cardBg: isDark ? '#1E293B' : '#FFF',
  cardBgAlt: isDark ? '#334155' : '#F8FAFC',
  textMain: isDark ? '#F8FAFC' : '#1D3557',
  textSub: isDark ? '#94A3B8' : '#457B9D',
  textMuted: isDark ? '#64748B' : '#94A3B8',
  border: isDark ? '#334155' : '#F0F0F0',
  borderAlt: isDark ? '#475569' : '#EEE',
  primary: isDark ? '#EF4444' : '#E63946',
  info: isDark ? '#38BDF8' : '#457B9D',
  navBg: isDark ? '#1E293B' : '#FFF',
  inputBg: isDark ? '#0F172A' : '#F1F5F9',
  loginBg: isDark ? '#020617' : '#1D3557',
  success: '#22C55E',
  successBg: isDark ? '#064E3B' : '#F0FDF4',
  dangerBg: isDark ? '#450A0A' : '#FEF2F2',
  dangerBorder: isDark ? '#7F1D1D' : '#FECACA',
  iconDef: isDark ? '#94A3B8' : '#CCC'
});

export const getStyles = (colors) => StyleSheet.create({
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background },
  centerPadded: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background, padding: 30 },
  retryButton: { marginTop: 20, backgroundColor: colors.primary, paddingVertical: 12, paddingHorizontal: 24, borderRadius: 10 },
  retryButtonText: { color: '#FFF', fontWeight: 'bold' },
  errorText: { color: colors.textMain, textAlign: 'center', marginTop: 15, fontSize: 14 },
  loginContainer: { flex: 1, backgroundColor: colors.loginBg, justifyContent: 'center' },
  themeToggleLogin: { position: 'absolute', top: Platform.OS === 'ios' ? 60 : 40, right: 25, zIndex: 10, padding: 10 },
  headerLogin: { alignItems: 'center', marginBottom: 30 },
  brandTitle: { fontSize: 32, fontWeight: 'bold', color: '#FFF' },
  loginCard: { backgroundColor: colors.cardBg, marginHorizontal: 30, padding: 25, borderRadius: 25 },
  loginCardTitle: { fontSize: 18, fontWeight: 'bold', color: colors.textMain, marginBottom: 20, textAlign: 'center' },
  input: { backgroundColor: colors.inputBg, color: colors.textMain, padding: 15, borderRadius: 12, marginBottom: 15, borderWidth: 1, borderColor: colors.borderAlt },
  inputRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.inputBg, borderRadius: 12, marginBottom: 15, borderWidth: 1, borderColor: colors.borderAlt },
  inputRowField: { flex: 1, color: colors.textMain, padding: 15 },
  inputRowIcon: { paddingHorizontal: 15 },
  primaryButton: { backgroundColor: colors.primary, padding: 18, borderRadius: 12, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 10 },
  primaryButtonDisabled: { opacity: 0.6 },
  buttonText: { color: '#FFF', fontWeight: 'bold' },
  switchText: { color: colors.textSub, textAlign: 'center', fontWeight: 'bold' },
  mainContainer: { flex: 1, backgroundColor: colors.background },
  topNav: { paddingHorizontal: 20, paddingBottom: 15, borderBottomWidth: 1, borderBottomColor: colors.border, backgroundColor: colors.navBg, flexDirection: 'row', justifyContent: 'space-between', paddingTop: Platform.OS === 'ios' ? 50 : 20 },
  navTitle: { fontSize: 16, fontWeight: 'bold', color: colors.textMain },
  roleTag: { fontSize: 10, color: colors.primary, fontWeight: 'bold' },
  navActions: { flexDirection: 'row', alignItems: 'center', gap: 20 },
  logoutBtn: { flexDirection: 'row', alignItems: 'center' },
  padding: { padding: 20 },
  sectionTitle: { fontSize: 22, fontWeight: 'bold', color: colors.textMain, marginBottom: 15 },
  subTitle: { fontWeight: 'bold', color: colors.textSub, marginBottom: 15 },

  dateGroup: { marginBottom: 15, backgroundColor: colors.cardBg, borderRadius: 12, overflow: 'hidden', borderWidth: 1, borderColor: colors.border, elevation: 1 },
  dateHeader: { backgroundColor: colors.loginBg, paddingVertical: 10, paddingHorizontal: 15, color: '#FFF', fontWeight: 'bold', fontSize: 14 },
  myShiftRowGrouped: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 12, borderBottomWidth: 1, borderBottomColor: colors.borderAlt, backgroundColor: colors.cardBg },

  userName: { fontWeight: 'bold', color: colors.textMain },
  userCard: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 18, backgroundColor: colors.successBg, borderRadius: 15, marginBottom: 10 },
  userCardMember: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 15, backgroundColor: colors.cardBg, borderRadius: 12, marginBottom: 10, borderWidth: 1, borderColor: colors.borderAlt },
  roleBadge: { fontSize: 10, fontWeight: '900', color: colors.textSub, marginTop: 4 },
  progressBg: { height: 10, backgroundColor: colors.borderAlt, borderRadius: 5, overflow: 'hidden' },
  progressFill: { height: '100%', backgroundColor: colors.success },
  percentText: { textAlign: 'right', fontSize: 12, fontWeight: 'bold', color: colors.success, marginTop: 5, marginBottom: 20 },
  bottomBar: { flexDirection: 'row', height: 90, borderTopWidth: 1, borderTopColor: colors.border, backgroundColor: colors.navBg, justifyContent: 'space-around', alignItems: 'center', paddingBottom: 25 },
  navItem: { alignItems: 'center' },
  navText: { fontSize: 9, marginTop: 5, fontWeight: 'bold', color: colors.textSub },
  emptyText: { textAlign: 'center', color: colors.textMuted, marginTop: 20 },
  gridContainer: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginBottom: 20 },
  moduleCard: { width: '48%', backgroundColor: colors.cardBgAlt, padding: 12, borderRadius: 15, marginBottom: 10, alignItems: 'center', borderWidth: 1, borderColor: colors.borderAlt },
  moduleTitle: { fontSize: 10, fontWeight: 'bold', marginTop: 5, textAlign: 'center', color: colors.textMain },
  moduleCount: { fontSize: 9, color: colors.primary, fontWeight: 'bold' },
  userFolderCard: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 18, backgroundColor: colors.cardBg, borderRadius: 15, marginBottom: 10, borderWidth: 1, borderColor: colors.border },
  userSub: { fontSize: 12, color: colors.success, fontWeight: 'bold' },
  backLink: { color: colors.primary, marginBottom: 15, fontWeight: 'bold' },
  folderSection: { marginBottom: 20 },
  folderSubtitle: { fontSize: 16, fontWeight: 'bold', borderBottomWidth: 2, borderBottomColor: colors.borderAlt, color: colors.textMain, paddingBottom: 5, marginBottom: 10 },
  goalRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, gap: 15 },
  goalText: { fontSize: 14, color: colors.textMain },
  alertItem: { padding: 15, backgroundColor: colors.cardBg, borderRadius: 12, marginBottom: 12, borderLeftWidth: 6, elevation: 2 },
  alertHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 5, gap: 8 },
  alertLevelText: { fontWeight: 'bold', fontSize: 12 },
  alertTitleText: { fontSize: 16, fontWeight: 'bold', color: colors.textMain },
  alertDate: { fontSize: 10, color: colors.textMuted, marginTop: 5 },
  unreadBadge: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.primary },
  badge: { position: 'absolute', right: -6, top: -4, backgroundColor: colors.primary, borderRadius: 10, width: 18, height: 18, justifyContent: 'center', alignItems: 'center' },
  badgeText: { color: '#FFF', fontSize: 10, fontWeight: 'bold' },
  adminForm: { backgroundColor: colors.cardBgAlt, padding: 15, borderRadius: 15, borderWidth: 1, borderColor: colors.borderAlt, marginBottom: 20 },
  levelRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 15 },
  levelBtn: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8, borderWidth: 1, borderColor: colors.border },
  levelBtnText: { fontSize: 11, fontWeight: 'bold', color: colors.textMuted },
  alertSubmit: { backgroundColor: colors.loginBg, padding: 12, borderRadius: 10, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 10 },
  deleteAlertBtn: { position: 'absolute', right: 10, bottom: 10 },
  userRole: { color: colors.textMuted, fontSize: 12 },
  documentCard: { flexDirection: 'row', alignItems: 'center', padding: 15, backgroundColor: colors.cardBg, borderRadius: 12, marginBottom: 10, borderWidth: 1, borderColor: colors.borderAlt, borderLeftWidth: 5, borderLeftColor: colors.textSub },
  documentTitle: { fontSize: 14, fontWeight: 'bold', color: colors.textMain },
  documentUrl: { fontSize: 10, color: colors.textMuted, marginTop: 4 },
  demoCard: { backgroundColor: colors.dangerBg, padding: 15, borderRadius: 15, borderWidth: 2, borderColor: colors.dangerBorder, borderStyle: 'dashed' },
  demoButton: { backgroundColor: colors.primary, padding: 12, borderRadius: 8, alignItems: 'center' },
  demoButtonText: { color: '#FFF', fontWeight: 'bold', fontSize: 14 },
  dangerZone: { backgroundColor: colors.dangerBg, borderBottomWidth: 1, borderColor: colors.dangerBorder },
  interCard: { backgroundColor: colors.cardBg, padding: 15, borderRadius: 12, marginBottom: 12, borderWidth: 1, borderColor: colors.dangerBorder, borderLeftWidth: 6, borderLeftColor: colors.primary, elevation: 2 },
  interHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 5 },
  interType: { fontSize: 16, fontWeight: 'bold', color: colors.primary },
  interLocation: { fontSize: 13, color: colors.textMain, fontWeight: 'bold', marginTop: 5 },
  interVehicles: { fontSize: 12, color: colors.textMuted, marginTop: 5 },
  endBtn: { backgroundColor: colors.inputBg, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 6, borderWidth: 1, borderColor: colors.borderAlt },
  endBtnText: { fontSize: 10, fontWeight: 'bold', color: colors.textMuted }
});
